### PR TITLE
glob representation of files

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Could you please release this into npm registry as well may be as another version

**Comment by ariesb** [comment]
Sure will do a version increment.

**Comment by ghost** [comment]
Thanks @ariesb

**Comment by ariesb** [comment]
Have you published this to Bower repo? If not I could do so, if you need.

**Comment by ariesb** [comment]
Seems not, will publish to bower registry.

**Comment by ariesb** [comment]
Bumped the version on npm.

**Comment by ghost** [comment]
Thanks

**Pull request merged**
